### ISSUE TITLE
Doesn't show radius of multiple workers. 

### ISSUE THREAD

**Issue by ShibePrime** [fourbytes/pogomap#6]
My Current environment has a Frontend_launcher.bat with 
Start rethinkdb.exe
`Start runserver.py -os -k [mapkeyhere] -l`**CITYLOCATION 1 - OS**`-r 100 --db-name pogomap --db-user admin --db-host 127.0.0.1 --db-port 28015`

then 

A separate Worker_Launcher.bat with

`runserver.py -a google -u beep@boop.com -p P4ssw0rd -k [mapkeyhere] -l`**CITYLOCAION 1**`-r 10000 --db-name pogomap --db-user admin --db-host 127.0.0.1 --db-port 28015`

`runserver.py -a google -u beep@boop.com -p P4ssw0rd -k [mapkeyhere] -l`**CITYLOCATION 2**`-r 10000 --db-name pogomap --db-user admin --db-host 127.0.0.1 --db-port 28015`

When toggled the show radius option the map only shows radius of **CITYLOCATION 1 - OS** 

Wondering if we could show all scanned locations like AHAAAAAAA's does. 

Let me know if there's anything I can do to help. 

EDIT:
Then again maybe the intention of this project isn't to include support for multiple workers/scan locations?

**Comment by fourbytes** [comment]
I'm also using multiple workers in my setup so I'll see if I can get around to implementing this tonight. Will also try and improve support/documentation for multiple workers, considering separating the searcher from the web server completely.
